// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_First.Models;

public partial class CorseAndInstractor
{
    public string CourseName { get; set; }

    public string InstructorName { get; set; }
}