// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_First.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public int Duration { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int TopicId { get; set; }

    public virtual ICollection<CourseInst> CourseInsts { get; set; } = new List<CourseInst>();

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();

    public virtual Topic Topic { get; set; }
}