// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_First.Models;

public partial class CourseInst
{
    public int InsId { get; set; }

    public int CourseId { get; set; }

    public string Evaluate { get; set; }

    public virtual Course Course { get; set; }

    public virtual Instructor Ins { get; set; }
}