// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_First.Models;

public partial class Instructor
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Bouns { get; set; }

    public decimal Salary { get; set; }

    public string Address { get; set; }

    public decimal HourRate { get; set; }

    public int DeptId { get; set; }

    public virtual ICollection<CourseInst> CourseInsts { get; set; } = new List<CourseInst>();

    public virtual Department Department { get; set; }

    public virtual Department Dept { get; set; }
}