// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_First.Models;

public partial class StudCourse
{
    public int StudId { get; set; }

    public int CourseId { get; set; }

    public int Grade { get; set; }

    public virtual Course Course { get; set; }

    public virtual Student Stud { get; set; }
}